Gorm:
  Mysql:
    Dsn: root:314159.com@tcp(127.0.0.1:3306)/loveshop?charset=utf8mb4&parseTime=True&loc=Local
  Pool:
    MaxIdle: 10
    MaxOpen: 100
    MaxLifeTime: 3600

Cache:
  Redis:
    Addr: localhost:6379
    Password: 
    DB: 0
    PoolSize: 20
    DialTimeout: 500

Kafka:
  Addr: 124.222.158.8:9092

Jwt:
  Issuer: Riicarus
  Expire: 3600
  Secret: riicarus_token

Server:
  Port: 10000